channels:
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_varnish_de18cf2b1c
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_http_a508001713
    grants:
      - 0
      - 2
      - 3
  -
    id: diagnostics
    grants:
      - 3
